### ISSUE TITLE
Kafka Auth

### ISSUE THREAD

**Issue by KonstantinCodes** [SnuK87/keycloak-kafka#1]
Hey there, is it possible to run this with auth? I'm trying to make it work with SASL and it always runs into:
`javax.security.auth.login.LoginException: unable to find LoginModule class: org.jboss.as.security.remoting.RemotingLoginModule`

I assume this has to do with `Thread.currentThread().setContextClassLoader(null);`.

But I don't know, how to proceed here. Any Ideas?

Update: asked on https://stackoverflow.com/questions/57574901/kafka-java-client-classloader-doesnt-find-sasl-scram-login-class

**Comment by SnuK87** [comment]
Version 1.1.0 supports kafka client configuration. Only tested it with SSL/TLS though. 
Feel free to reopen when there are any issues with SASL
