### ISSUE TITLE
Support of Keycloak HA mode

### ISSUE THREAD

**Issue by marziman** [SnuK87/keycloak-kafka#14]
Hello @SnuK87 

thanks for your efforts!

We are thinking to use this extension to publish User events e.g. when a user is created.

How will it behave if we scale up the keycloak containers in a cluster and high-availability scenario? As we are serving millions of users, we can not use one single keyloack container.

Is this extension aware of the multiple keycloak instances? To avoid that kafka receives multiple time same event from just another keycloak

If yes, we might use and adjust for usage in 
production ☺️
Or you think we shall not use in production?

Thanks!

**Comment by SnuK87** [comment]
Hi @marziman 

Thanks for reaching out.

I'm using this extension in an HA environment with two Keycloak servers on docker swarm.
The extension is not aware of other Keycloak instances but it doesn't need to.

When a user sends a request then it will only be handled by a single Keycloak server, hence only one Keycloak server will produce the event to kafka.

![keycloak-kafka-ha](https://user-images.githubusercontent.com/5814797/141709475-44204c8d-40c7-4b5d-9220-bfc10fd94281.png)

This is a simple example setup. In this case the request will be be handled by `Keycloak 2`.

Hope this helps. If you have further questions feel free to ask.

**Comment by SnuK87** [comment]
Closed due to inactivity. Feel free to reopen if there are any further questions.
