### ISSUE TITLE
Support work with Keycloak based on Quarkus

### ISSUE THREAD

**Issue by alexted** [SnuK87/keycloak-kafka#16]
Hi! 
I would like to be able to use the plugin with the newest version of Keycloak. Do you have plans to update it to work with Keycloak based on Quarkus (17+)?

**Comment by eshepelyuk** [comment]
Did fhey changed SPI API ? If not - then plugin should work.
or am I missing smth ?

**Comment by alexted** [comment]
> Did fhey changed SPI API ? If not - then plugin should work. or am I missing smth ?

My problem was that none of the attached instructions to run this addon worked for Keycloak version 17 and higher. Then, it turned out that all I had to do was set the appropriate environment variables.

**Comment by akloster** [comment]
@alexted Could you give examples which environment variables you set and what you put in them? It's not quite clear to me yet. Thank you.

**Comment by SnuK87** [comment]
@alexted Thanks for the contribution. I merged your pull request. I was quite busy the last month due to a job change but I'm on vacation next week and I'm gonna update the projects dependencies to make sure that everything will work fine wit the latest keycloak release.

**Comment by redben** [comment]
Hi @SnuK87 
Do you have any suggestions on how to configure TLS on the Quarkus distribution?

**Comment by SnuK87** [comment]
@redben I updated the docs. Check out https://github.com/SnuK87/keycloak-kafka#kafka-client-using-secure-connection
