### ISSUE TITLE
Tried this module, and notice that it is not working.  

### ISSUE THREAD

**Issue by robles-dec** [SnuK87/keycloak-kafka#34]
Here is the results, when attempting to build using the ./kc.sh build 

Tried other images, but it seems thar the curl command is also no longer available after ver19 or higher of keycloak

**Comment by SnuK87** [comment]
@robles-dec Can you please add some details?
What did you execute?
What was the result?

I don't know what the purpose of ` ./kc.sh build` is?
You build this module with maven or you can just download a release.

**Comment by SnuK87** [comment]
Closing this for now. Feel free to reopen with some details.
