### ISSUE TITLE
LOGIN_ERROR event is not published in KAFKA

### ISSUE THREAD

**Issue by anuragpathak21** [SnuK87/keycloak-kafka#36]
I can see LOGIN events in the KAFAK topic configured but did not see LOGIN_ERROR event. I have verified that the LOGIN_ERROR is added to KAFKA_EVENTS environment variable.

**Comment by SnuK87** [comment]
It's working fine for me. Can you provide some configurations where I can see how you set the environment variables?

**Comment by anuragpathak21** [comment]
This is for anyone who face this issue, please make sure ther is no space between KAFKA_EVENTS.

Correct value example below:

KAFKA_EVENTS : LOGIN,LOGIN_ERROR,REGISTER
