### ISSUE TITLE
Adding this project in the list of extensions at keycloak.org

### ISSUE THREAD

**Issue by pedroigor** [SnuK87/keycloak-kafka#5]
Hi @SnuK87,

I'm one of the developers behind Keycloak.

Your project is really interesting and may help many others that also need to optimize how events are processed and stored.

I see a lot of benefits in using a Kafka-based Event Listener Provider, especially when dealing with a huge load of events and how these events are consumed later for audit purposes.

That said, are you interested in adding your project to our site [1]? Is it active and alive?

[1] https://www.keycloak.org/extensions.html

**Comment by SnuK87** [comment]
@pedroigor Thanks for reaching out to me. That sounds great!

The project is alive and used in our test environment. I will push the changes more frequently to keep this project up to date.

**Comment by SnuK87** [comment]
Closing this after no further response.
