### ISSUE TITLE
Compatibility for Keycloak v25

### ISSUE THREAD

**Issue by alfredopoveda** [SnuK87/keycloak-kafka#50]
This module does not work with keycloak v25. Is there a roadmap where they intend to provide support for keycloak v25?

**Comment by jtognazzi** [comment]
We just updated to Keycloak 25, but we did not noticed any error with the plugin.
What kind of error do you have ?

**Comment by SnuK87** [comment]
I tested the latest release on Keycloak 25.0.5 and it was working fine. https://github.com/SnuK87/keycloak-kafka/releases/tag/1.2.0

> does not work
That's not a lot of information to help you there. Do you get an error message or anything to narrow down the issue?

**Comment by apoveda25** [comment]
Hi @jtognazzi @SnuK87, thanks for replying!

The output of keycloak is as follows:

![imagen](https://github.com/user-attachments/assets/910a28ec-6cce-42fc-9b5d-a7793e742187)

This is my Dockerfile:

![image](https://github.com/user-attachments/assets/399b8584-6050-48ca-b129-912f1f1d8094)

This is my definition of keycloak:

![image](https://github.com/user-attachments/assets/816ecd80-773a-4b58-9794-8eda0c6141fb)

This is my definition of broker (redpanda === kafka):

![image](https://github.com/user-attachments/assets/6244989e-722d-4f62-a5d7-f9395bad5cda)

When updating a user, I don't get any errors from keycloak, the event just doesn't reach the broker, do you have any idea why?

Maybe I missed something.

**Comment by jtognazzi** [comment]
I checked again on our environment if the message was really produced and consume properly, and I can confirm that it works as before 😌 
I see you used the brand new 1.2.0 version of this plugin, maybe you could try to downgrade to the previous version 1.5.0 ?

**Comment by apoveda25** [comment]
Hi, I tried v1.1.5, v1.1.6 and v1.2.0. With none of them I was able to get keycloak events to reach kafka. I have tried another module for MQTT and this one works for me. (keycloak-event-listener-mqtt)[https://github.com/softwarefactory-project/keycloak-event-listener-mqtt]

**Comment by SnuK87** [comment]
Sorry but I'm not able to help you when you just post some screenshots.

Can you post your keycloak log file here?  Then I can check if the spi is loading correctly.
Or your docker-compose file, then I can run it locally and debug it.

**Comment by apoveda25** [comment]
Hi @SnuK87, i'm leaving you the Dockerfile and the docker-compose here, I hope with this you can replicate the error.

[Dockerfile.zip](https://github.com/user-attachments/files/17099985/Dockerfile.zip)
[docker-compose.zip](https://github.com/user-attachments/files/17099996/docker-compose.zip)

**Comment by SnuK87** [comment]
@apoveda25 You didn't configure the kafka-keycloak spi in your posted files.

**Comment by apoveda25** [comment]
Sorry, I sent you a later version of those files. This is the previous version in which I used the Kafka module.

[docker-compose.zip](https://github.com/user-attachments/files/17100790/docker-compose.zip)
[Dockerfile.zip](https://github.com/user-attachments/files/17100791/Dockerfile.zip)

**Comment by SnuK87** [comment]
Your topic name is invalid.
```
org.apache.kafka.common.errors.InvalidTopicException: Invalid topics: [oidc/changes]: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidTopicException: Invalid topics: [oidc/changes]
```

I don't know about redpanda and couldn't verify your setup but when I replace it with vanilla kafka then it's all working.
