### ISSUE TITLE
standalone.xml or standalone-ha.xml

### ISSUE THREAD

**Issue by canattofilipe** [SnuK87/keycloak-kafka#7]
@SnuK87, congratulations to this project.

During the manual installation it was used `standalone.xml` and automatic installation (CLI script) used `standalone-ha.xml`. Why ?, What is the correct ?

**Comment by SnuK87** [comment]
@canattofilipe Thanks for your feedback.

You can change the configuration file in the CLI script to `standalone.xml`. The subsystem part of the configs are afaik the same for the normal and the `ha `configuration.

The CLI script uses the `ha` config by default because I wrote this script mainly for a deployment in a docker environement and the keycloak docker image uses the `ha` configuration as default.

I will update the README to make it clear that the manual and the automatic installation can be used for both configurations.

Please let me know if you face any issues or if you have any further questions.

**Comment by SnuK87** [comment]
@canattofilipe I updated the installation guide.

I added the maven assembly plugin, so you don't have to download and install all the dependencies manually. You can now also download the bundled .jar from https://github.com/SnuK87/keycloak-kafka/releases/tag/1.0.0 .

Would like to get some feedback and if you face any issues

**Comment by canattofilipe** [comment]
> @canattofilipe Thanks for your feedback.
> 
> You can change the configuration file in the CLI script to `standalone.xml`. The subsystem part of the configs are afaik the same for the normal and the `ha `configuration.
> 
> The CLI script uses the `ha` config by default because I wrote this script mainly for a deployment in a docker environement and the keycloak docker image uses the `ha` configuration as default.
> 
> I will update the README to make it clear that the manual and the automatic installation can be used for both configurations.
> 
> Please let me know if you face any issues or if you have any further questions.

@SnuK87, Thanks for the clarification, your SPI is working fine in my project.
I would like to capture realm events too, but keycloak does not provide it by default. Do you know why ?

**Comment by canattofilipe** [comment]
> @canattofilipe I updated the installation guide.
> 
> I added the maven assembly plugin, so you don't have to download and install all the dependencies manually. You can now also download the bundled .jar from https://github.com/SnuK87/keycloak-kafka/releases/tag/1.0.0 .
> 
> Would like to get some feedback and if you face any issues

I will test this new approach and close the topic in case of success, thanks for helping.

**Comment by SnuK87** [comment]
> @SnuK87, Thanks for the clarification, your SPI is working fine in my project.
> I would like to capture realm events too, but keycloak does not provide it by default. Do you know why ?

What do you mean by realm events? All (or most) of the events are based on the realm and you can read the `realmId` of the event to see which realm triggered the event.

**Comment by canattofilipe** [comment]
> realmId

I mean as realm events things like create and remove a realm. Keycloak does not trigger events on these operations, take a look at https://stackoverflow.com/questions/54766636/keycloak-event-listener-provider-not-firing-new-realm-creation-event

**Comment by canattofilipe** [comment]
> > @SnuK87, Thanks for the clarification, your SPI is working fine in my project.
> > I would like to capture realm events too, but keycloak does not provide it by default. Do you know why ?
> 
> What do you mean by realm events? All (or most) of the events are based on the realm and you can read the `realmId` of the event to see which realm triggered the event.

I mean by realm events things like create and remove a realm, Keycloak does not trigger events on these operarions, take a look at https://stackoverflow.com/questions/54766636/keycloak-event-listener-provider-not-firing-new-realm-creation-event

**Comment by SnuK87** [comment]
Ok I see. Yes looks like there is no support for such events. You can create a ticket in Jira and hope it will be added soon or you can try some workarounds e.g. you can read the the `realmId` of  the events and if you see an unknown event then you know that a new realm was created

**Comment by canattofilipe** [comment]
> > @canattofilipe I updated the installation guide.
> > I added the maven assembly plugin, so you don't have to download and install all the dependencies manually. You can now also download the bundled .jar from https://github.com/SnuK87/keycloak-kafka/releases/tag/1.0.0 .
> > Would like to get some feedback and if you face any issues
> 
> I will test this new approach and close the topic in case of success, thanks for helping.

@SnuK87, the newer approach works fine, so I will close this issue.
